default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
development:
  <<: *default
  database: postal_codes_development
test:
  <<: *default
  database: postal_codes_test
production:
  <<: *default
  database: postal_codes_production
  username: postal_codes
  password: <%= ENV['POSTAL_CODES_DATABASE_PASSWORD'] %>
