default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: postgres
  password: toor
development:
  <<: *default
  database: postal_codes_development
test:
  <<: *default
  database: postal_codes_test
production:
  <<: *default
  database: postal_codes_production
